=== drOpen/Temp/DrTestXML/DrTestXML/DrData.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
    DrData.xsd - This XML Schema representation of data storage DrData in xml format, 1.0.1, April 20, 2014
    Copyright (c) 2013-2014 Kudryashov Andrey aka Dr
    Kudryashov Andrey <kudryashov.andrey at gmail.com>
  -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DDNode">
    <xs:annotation>
      <xs:documentation>Hierarchy data warehouse</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="DDAttributesCollection" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="DDNode" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required" >
        <xs:annotation>
          <xs:documentation>Name of node. This attribute is required.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="IsRoot" type="xs:boolean" use="optional" default="false">
        <xs:annotation>
          <xs:documentation>Attribute exhibition on the root node. This attribute is optional and by default value is 'false'. This attribute information and is not used when creating an object.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="Children" type="xs:int" use="optional" default="0" >
        <xs:annotation>
          <xs:documentation>Attribute informs about the number of children node. This attribute is optional and by default value is '0'. This attribute information and is not used when creating an object.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute processContents="skip" />
    </xs:complexType>
  </xs:element>

  <xs:element name="DDAttributesCollection">
    <xs:annotation>
      <xs:documentation>Represents a named collection of DDValue.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="Attribute" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="Count" type="xs:int" use="optional" default="0" >
        <xs:annotation>
          <xs:documentation>Attribute informs about the number of attributes in collection. This attribute is optional and by default value is '0'. This attribute information and is not used when creating an object.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute processContents="skip" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Attribute">
    <xs:annotation>
      <xs:documentation>Represents access by name to DDValue.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="DDValue" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required" >
        <xs:annotation>
          <xs:documentation>Name of attribute. This attribute is required.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute processContents="skip" />
    </xs:complexType>
  </xs:element>

  <xs:element name="DDValue">
    <xs:annotation>
      <xs:documentation>Data warehouse.</xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="Value" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute ref="Type" use="required" >
        <xs:annotation>
          <xs:documentation>Data type.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="Size" use="optional" default="0">
        <xs:annotation>
          <xs:documentation>Attribute informs about the size of value. This attribute is optional and by default value is '0'. This attribute information and is not used when creating an object.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute processContents="skip" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Value">
    <xs:annotation>
      <xs:documentation>Element of array.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:attribute name="Type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="System.Char"/>
        <xs:enumeration value="System.Char[]"/>
        <xs:enumeration value="System.String"/>
        <xs:enumeration value="System.String[]"/>
        <xs:enumeration value="System.Boolean"/>
        <xs:enumeration value="System.Boolean[]"/>
        <xs:enumeration value="System.String[]"/>
        <xs:enumeration value="System.Int32"/>
        <xs:enumeration value="System.Int32[]"/>
        <xs:enumeration value="System.Single"/>
        <xs:enumeration value="System.Single[]"/>
        <xs:enumeration value="System.Int64"/>
        <xs:enumeration value="System.Int64[]"/>
        <xs:enumeration value="System.DateTime"/>
        <xs:enumeration value="System.DateTime[]"/>
        <xs:enumeration value="System.Byte"/>
        <xs:enumeration value="System.Byte[]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

</xs:schema>

=== drOpen/Temp/DrTestXML/DrTestXML/DrTestAction.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  DrTestAction.xml - XML serialization of DrTestAction as an object DrData 1.0.3, January 24, 2016 
 
  Copyright (c) 2013-2016 Kudryashov Andrey aka Dr
 
  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

      1. The origin of this software must not be misrepresented; you must not
      claim that you wrote the original software. If you use this software
      in a product, an acknowledgment in the product documentation would be
      appreciated but is not required.

      2. Altered source versions must be plainly marked as such, and must not be
      misrepresented as being the original software.

      3. This notice may not be removed or altered from any source distribution.

      Kudryashov Andrey <kudryashov.andrey at gmail.com>
-->
<DDNode Name="GUID" Type="DrTestAction" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DrData.xsd">
  <DDAttributesCollection>
    <Attribute Name="Variables" >
      <DDValue Type="System.String">./Variables</DDValue>
    </Attribute>
    <Attribute Name="Properties" >
      <DDValue Type="System.String">./Properties</DDValue>
    </Attribute>
    <Attribute Name="Inclusions" >
      <DDValue Type="System.String">./Properties/Inclusions</DDValue>
    </Attribute>
    <Attribute Name="Statistics">
      <DDValue Type="System.String">./Statistics</DDValue>
    </Attribute>
    <Attribute Name="Actions">
      <DDValue Type="System.String">./Arguments</DDValue>
    </Attribute>
  </DDAttributesCollection>
  <DDNode Name="Variables" Type="DrTestVariables">
    <DDAttributesCollection>
      <Attribute Name="Var1">
        <DDValue Type="System.String">Vars1</DDValue>
      </Attribute>
      <Attribute Name="Var2">
        <DDValue Type="System.Int32">0</DDValue>
      </Attribute>
    </DDAttributesCollection>
  </DDNode>
  <DDNode Name="Poperties" Type="DrTestActionProperties">
    <DDAttributesCollection>
      <Attribute Name="Library">
        <DDValue Type="System.String">library.dll</DDValue>
      </Attribute>
      <Attribute Name="Class">
        <DDValue Type="System.String">Class.Full.Name</DDValue>
      </Attribute>
      <Attribute Name="Method">
        <DDValue Type="System.String">Test</DDValue>
      </Attribute>
      <Attribute Name="Id">
        <DDValue Type="System.String">Id</DDValue>
      </Attribute>
      <Attribute Name="Name">
        <DDValue Type="System.String">Action Name</DDValue>
      </Attribute>
      <Attribute Name="Description">
        <DDValue Type="System.String">Description</DDValue>
      </Attribute>
      <Attribute Name="Status">
        <DDValue Type="System.String">Skipped</DDValue>
      </Attribute>
      <Attribute Name="ErrorHandling">
        <DDValue Type="System.String">Ignore</DDValue>
        <!--Stop + ToDo: Continue-->
      </Attribute>
    </DDAttributesCollection>
    <DDNode Name="Inclusions" Type="DrTestInclusions">
      <DDAttributesCollection>
        <Attribute Name="Tags" >
          <DDValue Type="System.String">./Tags</DDValue>
        </Attribute>
        <Attribute Name="Features" >
          <DDValue Type="System.String">./Features</DDValue>
        </Attribute>
        <Attribute Name="Categories" >
          <DDValue Type="System.String">./Categories</DDValue>
        </Attribute>
      </DDAttributesCollection>
      <DDNode Name="Tags" Type="DrTestInclusions">
        <DDAttributesCollection>
          <Attribute Name="Value">
            <DDValue Type="System.String[]">
              <Value>TagA</Value>
              <Value>TagB</Value>
            </DDValue>
          </Attribute>
        </DDAttributesCollection>
      </DDNode>
      <DDNode Name="Features" Type="DrTestInclusions">
        <DDAttributesCollection>
          <Attribute Name="Value">
            <DDValue Type="System.String[]">
              <Value>FeatureA</Value>
              <Value>FeatureB</Value>
            </DDValue>
          </Attribute>
        </DDAttributesCollection>
      </DDNode>
      <DDNode Name="Categories" Type="DrTestInclusions">
        <DDAttributesCollection>
          <Attribute Name="Value">
            <DDValue Type="System.String[]">
              <Value>CategoryA</Value>
              <Value>CategoryB</Value>
            </DDValue>
          </Attribute>
        </DDAttributesCollection>
      </DDNode>
    </DDNode>
  </DDNode>
  <DDNode Name="Statistics" Type="DrTestActionStatistics">
    <DDAttributesCollection>
      <Attribute Name="StartDate">
        <DDValue Type="System.DateTime">2013-06-17T15:25:01.0000000+04:00</DDValue>
      </Attribute>
      <Attribute Name="EndDate">
        <DDValue Type="System.DateTime">2013-06-17T15:25:01.0000000+04:00</DDValue>
      </Attribute>
      <Attribute Name="Total">
        <DDValue Type="System.Int32">0</DDValue>
      </Attribute>
      <Attribute Name="Passed">
        <DDValue Type="System.Int32">0</DDValue>
      </Attribute>
      <Attribute Name="Failed">
        <DDValue Type="System.Int32">0</DDValue>
      </Attribute>
      <Attribute Name="Skipped">
        <DDValue Type="System.Int32">0</DDValue>
      </Attribute>
      <Attribute Name="Disabled">
        <DDValue Type="System.Int32">0</DDValue>
      </Attribute>
    </DDAttributesCollection>
  </DDNode>
  <DDNode Name="Arguments" Type="DrTestActionArguments">
    <DDAttributesCollection/>
    <DDNode Name="Arg1" Type="DrTestActionArgument">
      <DDAttributesCollection>
        <Attribute Name="Name">
          <DDValue Type="System.String">Arg1</DDValue>
        </Attribute>
        <Attribute Name="Value">
          <DDValue Type="System.Boolean">true</DDValue>
        </Attribute>
        <Attribute Name="PassingType">
          <DDValue Type="System.String">ByVal</DDValue>
        </Attribute>
      </DDAttributesCollection>
    </DDNode>
    <DDNode Name="Arg2" Type="DrTestActionArgument">
      <DDAttributesCollection>
        <Attribute Name="Name">
          <DDValue Type="System.String">Arg2</DDValue>
        </Attribute>
        <Attribute Name="Value">
          <DDValue Type="System.Int32">123</DDValue>
        </Attribute>
        <Attribute Name="PassingType">
          <DDValue Type="System.String">ByRef</DDValue>
        </Attribute>
        <Attribute Name="VarName">
          <DDValue Type="System.String">Var1</DDValue>
        </Attribute>
        <Attribute Name="VarType">
          <DDValue Type="System.String">ToDo</DDValue>
          <!--Temporary - current test only, for current test level, etc -->
        </Attribute>
      </DDAttributesCollection>
    </DDNode>
  </DDNode>
</DDNode>
